<?php

/**
 * @var mixed|null $query
 * @var mixed|null $results
 * @var mixed|null $result
 * @var mixed|null $dom
 * @var mixed|null $xpath
 * @var mixed|null $elements
 * @var mixed|null $text
 * @var mixed|null $link
 */

use MintyPHP\Session;

?>
<h1>Hello Bing</h1>
<form method="post">
    Search<br />
    <input name="q" value="<?php e($query); ?>" /><br />
    <br />
    <input type="submit" />
    <?php Session::getCsrfInput(); ?>
</form>
<ol>
    <?php foreach ($results as $result) : ?>
        <li><a href="<?php e($result['link']); ?>"><?php e($result['text']); ?></a></li>
    <?php endforeach; ?>
</ol>