<h1>API</h1>
<p>This is a reference of all global variables and functions.</p>
<pre>
Type    Function                            Location        Purpose          Level
=====================================================================================================
        e($variable)                        Template/View   Output           Public
        d($variable)                        Everywhere      Debugging        Public
array   Query::records($sql,...)            Action          Database query   Public
array   Query::one($sql,...)                Action          Database query   Public
array   Query::pairs($sql,...)              Action          Database query   Public
string  Query::value($sql,...)              Action          Database query   Public
integer Query::insert($sql,...)             Action          Database query   Public
integer Query::update($sql,...)             Action          Database query   Public
bool    Auth::login($username,$password)    Action          Logging in       Public
bool    Auth::logout()                      Action          Logging out      Public
bool    Auth::register($username,$password) Action          Adding users     Public
        Router::addRoute($req,$loc)         Router Config   Routing          Public
        Router::redirect($url)              Action          Redirection      Public
string  Session::getCsrfInput()             Template/View   Form security    Public
=====================================================================================================
bool    Loader::register($path,$namespace)  Loader Config   Loading classes  Advanced
        Buffer::set($name,$string)          Template        Create template  Medium
string  Buffer::get($name)                  Template        Create template  Medium
        Buffer::start($name)                Template        Create template  Medium
        Buffer::end($name)                  Template        Create template  Medium
</pre>
