<h1>API</h1>
<p>This is a reference of all global variables and functions.</p>
<pre>
Type    Function                            Location        Purpose          Level
=====================================================================================================
        e($variable)                        Template/View   Output string    Public
        j($variable)                        Template/View   Output JSON      Public
        d($variable)                        Everywhere      Debugging        Public
array   DB::select($sql,...)                Action          Database query   Public
array   DB::selectOne($sql,...)             Action          Database query   Public
string  DB::selectValue($sql,...)           Action          Database query   Public
array   DB::selectPairs($sql,...)           Action          Database query   Public
array   DB::selectValues($sql,...)          Action          Database query   Public
integer DB::insert($sql,...)                Action          Database query   Public
integer DB::update($sql,...)                Action          Database query   Public
integer DB::delete($sql,...)                Action          Database query   Public
array   Curl::call($method,$url,$data)      Action          Curl API call    Public
array   Curl::navigate($method,$url,$data)  Action          Curl API call    Public
bool    Auth::login($username,$password)    Action          Logging in       Public
bool    Auth::logout()                      Action          Logging out      Public
bool    Auth::register($username,$password) Action          Adding users     Public
        Flash::set($type,$message)          Action          Flash message    Public
array   Flash::get()                        Action          Flash message    Public
        Router::addRoute($req,$loc)         Router Config   Routing          Public
        Router::redirect($url)              Action          Redirection      Public
        Router::json($object)               View            JSON             Public
string  Session::getCsrfInput()             Template/View   Form security    Public
=====================================================================================================
bool    Loader::register($path,$namespace)  Loader Config   Loading classes  Advanced
        Buffer::set($name,$string)          Template        Create template  Medium
bool    Buffer::get($name)                  Template        Create template  Medium
        Buffer::start($name)                Template        Create template  Medium
        Buffer::end($name)                  Template        Create template  Medium
</pre>
<p>NB: If Location is 'Action', this means the calls should only be made from a '.php' file. 'View' and 'Template' have a '.phtml' extension.</p>
