<h1>Authenticate</h1>
<p>In "vendor/mindaphp/core/Auth.php" you find 3 functions that you can use anywhere.</p>
<h2>Login</h2>
<pre>Auth::login($username,$password)</pre>
<p>Call this function to authenticate a user, example:</p>
<pre>
if (Auth::login($username, $password)) {
  Router::redirect("admin");
} else {
  $error = "Username/password not valid";
}
</pre>
<h2>Logout</h2>
<pre>Auth::logout()</pre>
<p>Call this function to de-authenticate a user, example:</p>
<pre>
Auth::logout();
Router::redirect("login");
</pre>
<h2>Register</h2>
<pre>Auth::register($username,$password)</pre>
<p>Call this function to register a new user, example:</p>
<pre>
if (Auth::register($username, $password)) {
  Auth::login($username, $password);
  Router::redirect("admin");
} else {
  $error = "User can not be registered";
}
</pre>
<h1>Passwordless</h1>
<p>In "vendor/mindaphp/core/NoPassAuth.php" you find 4 functions that you can use anywhere.</p>
<h2>Token</h2>
<pre>NoPassAuth::token($username)</pre>
<p>Call this function to retrieve a login token, example:</p>
<pre>
$token = NoPassAuth::token($username);
if ($token) {
  mail($username,'token',Router::getBaseUrl().'login/'.$token);
} else {
  $error = "Username not valid";
}
</pre>
<h2>Login</h2>
<pre>NoPassAuth::login($token)</pre>
<p>Call this function to authenticate a user, example:</p>
<pre>
if (NoPassAuth::login($token)) {
  Router::redirect("admin");
} else {
  $error = "Token not valid";
}
</pre>
<h2>Logout</h2>
<pre>NoPassAuth::logout()</pre>
<p>Call this function to de-authenticate a user, example:</p>
<pre>
NoPassAuth::logout();
Router::redirect("login");
</pre>
<h2>Register</h2>
<pre>NoPassAuth::register($username)</pre>
<p>Call this function to register a new user, example:</p>
<pre>
if (NoPassAuth::register($username)) {
  $token = NoPassAuth::token($username);
  mail($username,'token',Router::getBaseUrl().'login/'.$token);
} else {
  $error = "User can not be registered";
}
</pre>
