<h1>Database</h1>
<p>This class provides 4 public methods and the parameters are:</p>
<p>These functions can be statically accessed from the global "Query" class.</p>
<h2>Query</h2>
<pre>Query::records($sql,$arg1,$arg2,...)</pre>
<p>Executes SQL containing "?" symbols. Every questionmark must be matched by an extra argument. Example:</p>
<pre>
$query = 'insert into users (username,password,salt,created) values (?,sha1(concat(?,?)),?,NOW())';
$success = Query::records($query,$username,$salt,$password,$salt);
</pre>
<p>Or when you want to iterate over records:</p>
<pre>
$users = Query::records('select * from users');

&lt;?php foreach ($users as $user): ?&gt;
&lt;li&gt;&lt;?php e($user['username']); ?&gt;&lt;/li&gt;
&lt;?php endforeach; ?&gt;
</pre>
<h2>Query one</h2>
<pre>Query::one($sql,$arg1,$arg2,...)</pre>
<p>Same as "records", but only returns the first record or false. Example:</p>
<pre>
$query = 'select * from users where username = ? and sha1(concat(salt,?)) = password limit 1';
$user = Query::one($query,$username,$password);
</pre>
<h2>Insert id</h2>
<pre>Query::id()</pre>
<p>Returns the "insert id" from the last executed SQL query. Example:</p>
<pre>
$query = 'insert into users (username,password,salt,created) values (?,sha1(concat(?,?)),?,NOW())';
$success = Query::records($query,$username,$salt,$password,$salt);
if ($success) {
  $userId = Query::id();
} else {
  $userId = false;
}
</pre>
<h2>Raw engine access</h2>
<pre>Query::handle()</pre>
<p>Returns the handle to the (e.g. MySQLi) engine. You normally do not need this.</p>
