<h1>Flash</h1>
<p>The instance is stored in the global "Flash" class.</p>
<p>Typical usage is that a page does something and then redirects or reloads.
To show the status of the action on the next page 'flash messages' are used.
They are typically represented in the view with a green yellow or red bar with a message inside.</p>  
<h2>set</h2>
<pre>Flash::set($type,$message)</pre>
<p>This stores a flash message of the specified type in the session. Every type can hold one single message. Last write wins. Example:</p>
<pre>
Flash::set('success','Your changes have been saved.')
</pre>
<p>NB: This should be called from an action (.php) not a view (.phtml), because then the session is already closed and cannot be written anymore.</p>
<h2>get</h2>
<pre>Flash::get()</pre>
<p>This gets and removes all flash messages from the session. Since the messages are removed you shoudl only call this function once. Example:</p>
<pre>
$flash=Flash::get();
</pre>
<p>NB: This should be called from an action (.php) not a view (.phtml), because then the session is already closed and cannot be written anymore.</p>