<h1>Flash</h1>
<p>The instance is stored in the global "Flash" class.</p>
<h2>set</h2>
<pre>Flash::set($type,$message)</pre>
<p>This stores a flash message of the specified type in the session. Example:</p>
<pre>
Flash::set('success','Your changes have been saved.')
</pre>
<p>NB: This should be called from an action (.php) not a view (.php), because then the session is already closed and cannot be written anymore.</p>
<h2>get</h2>
<pre>Flash::get()</pre>
<p>This gets and removes all flash messages from the session. Example:</p>
<pre>
$flash=Flash::get();
</pre>
<p>NB: This should be called from an action (.php) not a view (.php), because then the session is already closed and cannot be written anymore.</p>