<h1>Functions</h1>
<p>The two "shortcut" functions "d()" and "e()" can be used anywhere in your application.</p>
<h2>Escaped echo</h2>
<pre>e($variable)</pre>
<p>In the views one should use "&lt;?php e($variable); ?&gt;" to echo and NOT the normal "echo". 
This function escapes the variable (using "htmlspecialchars" with ENT_QUOTES flag and 'UTF-8' encoding)
to prevent Cross-Site-Scripting (XSS) attacks.</p>
<h2>Debug</h2>
<pre>d($variable)</pre>
<p>The "d" (for debug) function logs the contents of a variable to the "Logging" panel of the debugger.
In the debugger the file and line number of the invocation will also be logged.
If the debugger is not loaded (in production) then calls to the function are ignored.
To reduce memory usage this function limits the output:</p>
<ol>
<li>Only the first 100 characters of each string are logged.</li>
<li>Only the first 25 elements of an array are logged.</li>
<li>Only the first 10 levels of nested objects/arrays are logged.</li>
</ol>
<p>These 3 limits can be set using 3 optional parameters in the above order. 
Hence, calling "d($variable)" is equal to calling "d($variable,100,25,10)".</p>