<?php

/**
 * @var mixed|null $error
 */

use MintyPHP\Buffer;
use MintyPHP\Session;

Buffer::set('title', 'Login');
?>
<h1>Login</h1>
<form method="post">
    Username<br />
    <input name="username" /><br />
    Password<br />
    <input type="password" name="password" /> <a href="nopass/login">No password</a><br />
    <br />
    <input type="submit" /><br />
    <?php e($error); ?>
    <?php Session::getCsrfInput(); ?>
</form>

<p><a href="register">Register</a></p>