<?php

/**
 * @var mixed|null $error
 * @var mixed|null $username
 * @var mixed|null $password
 * @var mixed|null $password2
 */

use MintyPHP\Session;

?>
<h1>Register</h1>
<form method="post">
    Username<br />
    <input name="username" /><br />
    Password<br />
    <input type="password" name="password" /><br />
    Password (again)<br />
    <input type="password" name="password2" /><br />
    <br />
    <input type="submit" /><br />
    <?php e($error); ?>
    <?php Session::getCsrfInput(); ?>
</form>