<h1>Buffer</h1>
<p>The instance is stored in the global "Buffer" class.</p>
<h2>get/set</h2>
<pre>Router::get($name)</pre>
<p>This prints a string stored in a 'buffer' with the specified name or returns false when the buffer is not found. The name of the view buffer is 'html'.</p>
<pre>Router::set($name, $string)</pre>
<p>This stores a string into a 'buffer' with the specified name.</p>
<h2>start/end</h2>
<pre>Router::start($name)</pre>
<p>This starts a 'buffer' with the specified name.</p>
<pre>Router::end($name)</pre>
<p>This end a 'buffer' with the specified name.</p>