<h1>Database</h1>
<p>This class provides 8 public methods and the parameters are:</p>
<p>These functions can be statically accessed from the global "DB" class.</p>
<h2>Select</h2>
<pre>DB::select($sql,$arg1,$arg2,...)</pre>
<p>Executes SQL containing "?" symbols. Every questionmark must be matched by an extra argument. 
The following query retrieves all users that have an username starting with a 'M':</p>
<pre>
$users = DB::select('select * from users where username LIKE ?','M%');
</pre>
<p>In the view (.phtml) file we can iterate over records and print the usernames in a HTML list using:</p>  
<pre>
&lt;?php foreach ($users as $user): ?&gt;
&lt;li&gt;&lt;?php e($user['username']); ?&gt;&lt;/li&gt;
&lt;?php endforeach; ?&gt;
</pre>
<h2>Select one</h2>
<pre>DB::selectOne($sql,$arg1,$arg2,...)</pre>
<p>Same as "records", but only returns the first record or false. Example:</p>
<pre>
$query = 'select * from users where username = ? limit 1';
$user = DB::selectOne($query,$username);
</pre>
<h2>Insert</h2>
<pre>DB::insert()</pre>
<p>Executes SQL "INSERT" statement and returns the "insert id" from the last executed SQL query. Example:</p>
<pre>
$query = 'insert into users (username,password,created) values (?,?,NOW())';
$userId = DB::insert($query,$username,$password);
</pre>
<h2>Update</h2>
<pre>DB::update()</pre>
<p>Executes SQL "UPDATE" statement and returns the "affected rows" from the last executed SQL query. Example:</p>
<pre>
$query = 'update users set username = ? where id = ?';
$affectedRows = DB::update($query,$username,$userId);
</pre>
<h2>Delete</h2>
<pre>DB::delete()</pre>
<p>Executes SQL "DELETE" statement and returns the "affected rows" from the last executed SQL query. Example:</p>
<pre>
$query = 'delete from users where username = ?';
$affectedRows = DB::delete($query,$username);
</pre>
<h2>Query</h2>
<pre>DB::query()</pre>
<p>Executes other SQL statements and returns a boolean indicating success (true) or failure (false). Example:</p>
<pre>
$query = 'drop table users';
$success = DB::query($query);
</pre>