<h1>Router</h1>
<p>The instance is stored in the global "Router" class.</p>
<h2>Routes</h2>
<pre>Router::addRoute($request, $location)</pre>
<p>This should be called from the router configuration (in "config/router.php"). Typically this is used to route
the empty requested URL "/" to a specific location. It does not update the URL in the address bar. If you do want
to update the URL in the address bar you should use the "redirect" function.</p>
<h2>Request</h2>
<pre>Router::getRequest()</pre>
<p>With this call you can read the requested URL. Normally this is the same as "$_SERVER['REQUEST_URI']".</p>
<h2>URL</h2>
<pre>Router::getUrl()</pre>
<p>With this call you can find the effective routed URL. This does not contain parameters and/or trailing slashes.
It does also show the redirected target, not the entered URL.</p>
<pre>Router::getBaseUrl()</pre>
<p>With this call you can find the routed URL prefix. When not loaded in a subdirectory this should be "/".
It can be configured in the "config/config.php" file in the "Router" section.</p>
<h2>View</h2>
<pre>Router::getView()</pre>
<p>This gets the path to the view file that is loaded. For example on this page it returns: "pages/docs/router(docs).phtml".
<h2>Action</h2>
<pre>Router::getAction()</pre>
<p>This gets the path to the action file that is loaded. For example on this page it returns: false.
<h2>Template</h2>
<pre>Router::getTemplateView()</pre>
<p>This gets the path to the template view file that is loaded. For example on this page it returns: "templates/docs.phtml".
<pre>Router::getTemplateAction()</pre>
<p>This gets the path to the template action file that is loaded. For example on this page it returns: false.
<h2>Redirect</h2>
<pre>Router::redirect($url)</pre>
<p>This "redirect" function redirects directly to another URL.</p>
<h2>JSON</h2>
<pre>Router::json($object)</pre>
<p>This "json" function outputs a JSON object as a full response.</p>
